#----------------------------------------------
#   Config file for vumi_http_proxy.
#   Add all ip addresses to blacklist here
#----------------------------------------------
proxy-blacklist:
    # IPv4 ADDRESSES
    - '69.16.230.117'
    - '93.184.216.34'

    # IPv6 ADDRESSES
    - '2606:2800:220:1:248:1893:25c8:1946'

dns-servers:
    - ['8.8.8.8', 53]
    - ['8.8.4.4', 53]
